export enum Permission {

    SEE_OWN_DATA,
    SEE_GROUPMATES_DATA,
    SEE_PEOPLES_IN_THE_SAME_ORGANISATION_DATA,
    SEE_EVERYONES_DATA,

    CREATE_OWN_DATA,
    CREATE_GROUPMATES_DATA,
    CREATE_PEOPLES_IN_THE_SAME_ORGANISATION_DATA,
    CREATE_EVERYONES_DATA,

    CREATE_OWN_SERVERE_DATA,
    CREATE_GROUPMATES_SERVERE_DATA,
    CREATE_PEOPLES_IN_THE_SAME_ORGANISATION_SERVERE_DATA,
    CREATE_EVERYONES_SERVERE_DATA,

    UPDATE_OWN_DATA,
    UPDATE_GROUPMATES_DATA,
    UPDATE_PEOPLES_IN_THE_SAME_ORGANISATION_DATA,
    UPDATE_EVERYONES_DATA,

    UPDATE_OWN_SERVERE_DATA,
    UPDATE_GROUPMATES_SERVERE_DATA,
    UPDATE_PEOPLES_IN_THE_SAME_ORGANISATION_SERVERE_DATA,
    UPDATE_EVERYONES_SERVERE_DATA,

    REMOVE_OWN_DATA,
    REMOVE_GROUPMATES_DATA,
    REMOVE_PEOPLES_IN_THE_SAME_ORGANISATION_DATA,
    REMOVE_EVERYONES_DATA,

    REMOVE_OWN_SERVERE_DATA,
    REMOVE_GROUPMATES_SERVERE_DATA,
    REMOVE_PEOPLES_IN_THE_SAME_ORGANISATION_SERVERE_DATA,
    REMOVE_EVERYONES_SERVERE_DATA,

    ADVANCE_TO_THE_LOWER_LEVEL_WHICH_IS_ADVISOR,
    ADVANCE_TO_THE_SAME_LEVEL_WHICH_IS_ADVISOR,

    DISADVANCE_FROM_THE_LOWER_LEVEL_WHICH_IS_DISADVISOR,
    DISADVANCE_FROM_THE_SAME_LEVEL_WHICH_IS_DISADVISOR,
}