name: test

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm --prefix ./server ci
      - run: npm run --prefix ./server build

      - run: npm --prefix ./web ci
      - run: npm run --prefix ./web build